### ISSUE TITLE
Error with ChromeDriver 75

### ISSUE THREAD

**Issue by mikedijkstra** [dbalatero/capybara-chromedriver-logger#11]
With the release of Chrome 75 (and ChromeDriver 75) we started seeing this error:

```ruby
Capybara::Chromedriver::Logger::TestHooks.after_example! NoMethodError: private method `log' called for #<Selenium::WebDriver::Remote::W3C::Bridge:0x00007fad79f94218>
```

ChromeDriver 75 [now runs in W3C standard compliant mode by default](http://chromedriver.chromium.org/downloads).

Which ultimately means that `driver.browser.manage.logs.get(:browser)` is not a compliant way to get access to the logs.

I wasn't able to figure out the correct way to access the logs but I was able to get our test suite to continue running by adding the following capabilities:

```ruby
capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
   …
    chromeOptions: {
      w3c: false
    }
  )
```

**Comment by dbalatero** [comment]
@michaeldijkstra I fixed this in master and 0.3.0. If you check the readme there is a new way to wrap capabilities so we can have a bit better control over future updates like this.
