### ISSUE TITLE
Nothing in the documentation mentions where one expects to see the logged output

### ISSUE THREAD

**Issue by derrelldurrett** [dbalatero/capybara-chromedriver-logger#15]
I scoured your docs for evidence of where the output should be expected. I don't see that. I presume I'm missing something (like I'm expecting to have there be a default location, and there isn't?), but I'm not even sure what else that may be.

What am I missing? Do you need more information? I am attempting to use this in Cucumber rather than just RSpec, so perhaps that's it?

**Comment by dbalatero** [comment]
@derrelldurrett The log destination defaults to STDOUT:

https://github.com/dbalatero/capybara-chromedriver-logger/blob/60e7a9c6bc8bbe5e4dc1f508a57e5d4c6cac3d53/lib/capybara/chromedriver/logger/collector.rb#L7

I haven't used Cucumber in years, so I can't help you there.

However, you basically need to setup a hook that runs after each test, as in:

https://github.com/dbalatero/capybara-chromedriver-logger/blob/60e7a9c6bc8bbe5e4dc1f508a57e5d4c6cac3d53/README.md#L59-L67
