### ISSUE TITLE
JS Errors No Longer Raise Exception

### ISSUE THREAD

**Issue by tubbo** [dbalatero/capybara-chromedriver-logger#26]
When raising an error in JavaScript like this:

```javascript
throw new Error("something really bad happened")
```

The output I get in tests is:

```
📜   info  http://127.0.0.1:53290/assets/workarea/storefront/application-ffddb2f6eec9d590acaf366c1cb3ace1844c76cbc94403b50cec57eabc11f69d.js 48170:61573
     Error: something really bad happened
```

I have the following config set in my base System Test class:

```ruby
# Fail tests when JS errors are thrown.
Capybara::Chromedriver::Logger.raise_js_errors = true

# Ignore common error responses for `/current_user.json` and /login`.
# These occur during the normal course of testing authentication, so
# they don't need to be output in the test results.
Capybara::Chromedriver::Logger.filters = [
  /(login|current_user\.json) - Failed to load resource: the server responded with a status of (401|422)/
]
```

I did some digging into the raw log message and it turns out this is happening because thrown errors in Chrome (at least as of my browser version, 85) don't seem to be getting the "SEVERE" log level, like the gem expects. Instead, its log level is "INFO", so these errors are somewhat indistinguishable from regular old console messages.

I was able to fix it and get the `JsErrors` exception to throw by monkey-patching this:

```ruby
class Capybara::Chromedriver::Logger::Message do
  def error?
    super || message =~ /Error:/ || message =~ /Uncaught/
  end
end
```

Do you think this is a regression that happened upstream, or was it intentional for these error messages to have log level "INFO"? If it's the latter, I'll be happy to PR my changes.

**Comment by dbalatero** [comment]
> I did some digging into the raw log message and it turns out this is happening because thrown errors in Chrome (at least as of my browser version, 85) don't seem to be getting the "SEVERE" log level, like the gem expects. Instead, its log level is "INFO", so these errors are somewhat indistinguishable from regular old console messages.

That's pretty wild - I'd think errors would not be at the `info` level. This feels like a Chrome regression? Does the error show up in red in the console still?

Ugh. I'm fine with upstreaming this though, if they are truly all marked `INFO` level...

**Comment by tubbo** [comment]
Same here, definitely seems like an uncaught regression upstream...
