### ISSUE TITLE
Cucumber support

### ISSUE THREAD

**Issue by zedtux** [dbalatero/capybara-chromedriver-logger#27]
Would be awesome with Cucumber too :smiley:

**Comment by dbalatero** [comment]
You'll have to add a thin wrapper and send a PR. I haven't used Cucumber since circa 2010 and have no plans to add support for it at this time. I don't mind merging a patch though.

**Comment by zedtux** [comment]
Good to know, thank you.

**Comment by dbalatero** [comment]
Closing this, but feel free to reopen if you have a patch!
