### ISSUE TITLE
filters are ignored for any "SEVERE" level message

### ISSUE THREAD

**Issue by joekrill** [dbalatero/capybara-chromedriver-logger#6]
As far as I can tell `filters` are only applied when outputting to the `log_destination` and will not prevent exceptions from being raised.  The only thing that determines whether an exception is raised is if the level is "SEVERE" (and whether `raise_js_errors?` is enabled). That seems contrary to the documented behavior in the `README.md`:

```
# If you filter out any errors with the `filters` option, they will
# not trigger an exception in your spec examples.
``` 

In `flush_logs!` a message will get added to the `errors` collection based _solely_ on it's `error?` result (which simply checks `level == 'SEVERE'`). The filter is only applied _after_ that, when outputting the message to the `log_destination`:

```rb
def flush_logs!
  browser_logs.each do |log|
    message = Message.new(log)
    errors << message if message.error?

    log_destination.puts message.to_s unless should_filter?(message)
  end
end
```

Then when `raise_errors_if_needed!` is called (right after `flush_logs`) it only checks the array of `errors` which is unaffected by any filters:

```
def raise_errors_if_needed!
  return unless Capybara::Chromedriver::Logger.raise_js_errors?
  return if errors.empty?

  formatted_errors = errors.map(&:to_s)
  error_list = formatted_errors.join("\n")

  raise JsError, "Got some JS errors during testing:\n\n#{error_list}"
end
```

What is the behavior supposed to be here? It seems to me that any errors matching any `filters` should be _completely_ ignored and not raise. I'm not sure if I'm missing something here or if I'm misunderstanding the docs. I'm happy to put up a PR, but just want to verify the desired behavior here.

**Comment by joekrill** [comment]
I decided to put up a PR anyway (#7), since I needed the change for my project anyway.

**Comment by joshlarsen** [comment]
Thanks @joekrill, I needed this as well.
