### ISSUE TITLE
Will this work with Minitest?

### ISSUE THREAD

**Issue by okor** [dbalatero/capybara-chromedriver-logger#8]
The functionality here matches my use case quite well, thanks for the gem! I do however use Minitest and was wondering if this gem was compatible. Thanks!

**Comment by logankoester** [comment]
I'm using it with Minitest, no problem. Just call


```ruby
Capybara::Chromedriver::Logger::TestHooks.after_example!
```

from a hook that runs after each test.

**Comment by dbalatero** [comment]
Thanks @logankoester!
